### ISSUE TITLE
Add LICENSE file to the project

### ISSUE THREAD

**Issue by minnukota381** [kavyaballa1020/Angular-Portfolio#1]
The repository is missing a LICENSE file. To make the project open source and specify usage rights, we need to add a LICENSE file.

Suggested steps:
1. Choose an appropriate open-source license (e.g., MIT, Apache 2.0).
2. Add a LICENSE file in the root directory of the repository.

For more information on open-source licenses, refer to [Choose a License](https://choosealicense.com/).

**Comment by kavyaballa1020** [comment]
Thanks for contributing!
